artifacts_root: "artifacts"

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "https://github.com/codewithabdou/datasets/raw/refs/heads/main/cat-dog-data.zip"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion"
