from CatsVsDogs.pipeline.stage_02_base_model_prepration import BaseModelPreparationPipeline
from CatsVsDogs.pipeline.stage_01_data_ingestion import DataIngestionTrainingPipeline
from CatsVsDogs.pipeline.stage_03_training import TrainingPipeline